# Use a base image with Java 17
FROM openjdk:17 AS base

# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR file from the local machine to the container
COPY target/*.jar app.jar

# Expose the port the app will run on
EXPOSE 8989

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
